# Generated by Django 5.2.7 on 2025-10-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pet_match', 'Potential Pet Match'), ('request_update', 'Request Status Update'), ('new_pet_report', 'New Pet Report'), ('system_message', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_pet_id', models.IntegerField(blank=True, null=True)),
                ('related_request_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Calculated similarity score between pets')),
                ('match_factors', models.JSONField(help_text='Factors that contributed to the match')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('found_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='pets.pet')),
                ('lost_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='pets.pet')),
            ],
            options={
                'ordering': ['-similarity_score', '-created_at'],
                'unique_together': {('found_pet', 'lost_pet')},
            },
        ),
    ]
