# Generated by Django 5.2.7 on 2025-10-22 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PetReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_name", models.CharField(blank=True, max_length=120)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=120)),
                ("color", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("location_found", models.CharField(max_length=255)),
                ("date_found", models.DateField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="pet_photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("found", "Found"),
                            ("claimed", "Claimed"),
                            ("closed", "Closed"),
                        ],
                        default="found",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pet_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimer_name", models.CharField(max_length=120)),
                ("claimer_email", models.EmailField(max_length=254)),
                ("claimer_phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                (
                    "proof_photo",
                    models.ImageField(blank=True, null=True, upload_to="claim_proofs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="pets.petreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="petreport",
            index=models.Index(
                fields=["species", "color"], name="pets_petrep_species_0f85f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="petreport",
            index=models.Index(
                fields=["status", "date_found"], name="pets_petrep_status_39b4a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="claim",
            constraint=models.UniqueConstraint(
                fields=("pet", "claimer_email"), name="unique_claim_per_pet_email"
            ),
        ),
    ]
