# Generated by Django 5.2.7 on 2025-10-22 02:22

import django.utils.timezone
import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, editable=False, help_text="Public code to check this report's status.", max_length=12, unique=True)),
                ('report_type', models.CharField(choices=[('found', 'Found'), ('lost', 'Lost')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('matched', 'Matched'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], db_index=True, max_length=16)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(blank=True, db_index=True, max_length=120)),
                ('distinctive_marks', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(help_text='Area where pet was lost/found', max_length=200)),
                ('date_seen', models.DateField(db_index=True, help_text='Date pet was lost/found')),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photo_upload_path)),
                ('reporter_name', models.CharField(max_length=120)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'species', 'color'], name='pets_petrep_report__7ee496_idx'), models.Index(fields=['status', 'date_seen'], name='pets_petrep_status_a92723_idx')],
            },
        ),
    ]
