# Generated by Django 5.2.7 on 2025-10-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petreport",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="petreport",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="petreport",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
